### ISSUE TITLE
Feature Request: Add option for Bootstrap Version

### ISSUE THREAD

**Issue by anthony0030** [jerryklimcik/alfred-bootstrap-docs#2]
It would be great if there was a configuration option to set the bootstrap version.
I am using bootstrap 5.2 but the workflow searches 5.1, I figured out you need to change the version in the PHP file.
I really like how this workflow works! Good work!

**Comment by jerryklimcik** [comment]
Hi @anthony0030, thank you. I released new version with 5.2. and I also [added option to switch another 5.x branch](https://github.com/jerryklimcik/alfred-bootstrap-docs#changing-versions)

**Comment by anthony0030** [comment]
Hi @jerryklimcik Thank you for the quick implementation 👍🏻
